import fs from "node:fs/promises";
import path from "node:path";
import type { AdapterRuntimeMcpServer } from "@paperclipai/adapter-utils";

/**
 * Grok discovers project-scoped MCP servers from `<cwd>/.grok/config.toml`,
 * walking from the execution directory up to the git root. A *project* config
 * may only contribute `[mcp_servers]`, `[plugins]` and `[permission]`, so the
 * file this module renders holds `[mcp_servers]` and nothing else.
 *
 * The managed `GROK_HOME` is deliberately not used for this: it is
 * company-scoped and shared by concurrent runs, while a Paperclip runtime MCP
 * token is minted per run. Writing a per-run token into a shared home would
 * race between runs and outlive the run that owns it.
 */
export const GROK_PROJECT_CONFIG_DIRNAME = ".grok";
export const GROK_PROJECT_CONFIG_FILENAME = "config.toml";

/**
 * Per-tool-call timeout written for every staged server. Grok defaults to 6000
 * seconds; a connector call that has not answered in two minutes is wedged, not
 * working, and an unattended run should not wait out the difference.
 */
export const DEFAULT_GROK_MCP_TOOL_TIMEOUT_SEC = 120;

/**
 * Escapes a value into a TOML basic string. Urls and bearer tokens are ASCII
 * in practice, but a connection-supplied name reaches this file as data, so the
 * structural characters and the control range are escaped rather than trusted.
 */
export function toTomlBasicString(value: string): string {
  let out = "";
  for (const char of value) {
    const code = char.codePointAt(0) ?? 0;
    if (char === "\\") out += "\\\\";
    else if (char === '"') out += '\\"';
    else if (char === "\n") out += "\\n";
    else if (char === "\r") out += "\\r";
    else if (char === "\t") out += "\\t";
    else if (code < 0x20 || code === 0x7f) out += "\\u" + code.toString(16).padStart(4, "0");
    else out += char;
  }
  return `"${out}"`;
}

/**
 * Normalizes a Paperclip server name into a TOML bare key. Paperclip names
 * carry spaces ("Paperclip connections"), which a bare key cannot hold, and a
 * bare key keeps the generated file readable without relying on quoted-key
 * handling.
 */
export function toGrokServerKey(name: string): string {
  const slug = name
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9_-]+/g, "_")
    .replace(/_{2,}/g, "_")
    .replace(/^[_-]+|[_-]+$/g, "");
  return slug.length > 0 ? slug : "mcp_server";
}

/** Renders the `[mcp_servers]` project config for one run. */
export function renderGrokMcpConfigToml(
  servers: AdapterRuntimeMcpServer[],
  input: { runId: string; toolTimeoutSec?: number },
): string {
  // Grok's own default is 6000 seconds, so one wedged tool call holds a run for
  // 100 minutes. A connector query answers in seconds; bound it by default and
  // let an agent that genuinely needs longer raise it.
  const toolTimeoutSec =
    typeof input.toolTimeoutSec === "number" && Number.isFinite(input.toolTimeoutSec) && input.toolTimeoutSec > 0
      ? Math.floor(input.toolTimeoutSec)
      : DEFAULT_GROK_MCP_TOOL_TIMEOUT_SEC;
  const lines: string[] = [
    "# Generated by Paperclip for run " + input.runId + ".",
    "# Removed when the run ends. Do not edit or commit this file.",
    "# A project config may only carry [mcp_servers], [plugins] and [permission].",
  ];
  const usedKeys = new Set<string>();
  for (const server of servers) {
    const base = toGrokServerKey(server.name);
    let key = base;
    if (usedKeys.has(key)) key = `${base}_${server.connectionId.slice(0, 8)}`;
    let suffix = 2;
    while (usedKeys.has(key)) {
      key = `${base}_${server.connectionId.slice(0, 8)}_${suffix}`;
      suffix += 1;
    }
    usedKeys.add(key);

    lines.push("");
    lines.push(`[mcp_servers.${key}]`);
    lines.push(`url = ${toTomlBasicString(server.url)}`);
    lines.push(`tool_timeout_sec = ${toolTimeoutSec}`);
    // The headers sub-table must follow every scalar key of its parent: TOML
    // closes the parent table once a sub-table is opened.
    if (server.token.trim().length > 0) {
      lines.push(`[mcp_servers.${key}.headers]`);
      lines.push(`Authorization = ${toTomlBasicString(`Bearer ${server.token}`)}`);
    }
  }
  return `${lines.join("\n")}\n`;
}

/**
 * Writes the project MCP config into the execution workspace. Returns the paths
 * that were created so the caller can remove them when the run ends.
 */
export async function writeGrokProjectMcpConfig(input: {
  cwd: string;
  servers: AdapterRuntimeMcpServer[];
  runId: string;
  toolTimeoutSec?: number;
}): Promise<{ configPath: string; configDir: string; createdDir: boolean }> {
  const configDir = path.join(input.cwd, GROK_PROJECT_CONFIG_DIRNAME);
  const configPath = path.join(configDir, GROK_PROJECT_CONFIG_FILENAME);
  const createdDir = await fs
    .access(configDir)
    .then(() => false)
    .catch(() => true);
  await fs.mkdir(configDir, { recursive: true });
  // The file carries a bearer token, so it is never group- or world-readable.
  await fs.writeFile(
    configPath,
    renderGrokMcpConfigToml(input.servers, {
      runId: input.runId,
      toolTimeoutSec: input.toolTimeoutSec,
    }),
    { mode: 0o600 },
  );
  return { configPath, configDir, createdDir };
}

/** The ignore entry added to the workspace's local git exclude file. */
export const GROK_GIT_EXCLUDE_ENTRY = ".grok/";

/**
 * Adds `.grok/` to the workspace's `.git/info/exclude`, so a run that stages a
 * bearer token into the working tree cannot commit it with a broad `git add`.
 * `info/exclude` is local to the clone and never itself committed, so this
 * leaves nothing behind in the repository.
 *
 * Best effort by design: a bare repo, a worktree whose `.git` is a file, or a
 * read-only `.git` all resolve false rather than failing the run. The staged
 * file is still removed when the run ends.
 */
export async function ensureGrokProjectConfigGitExcluded(cwd: string): Promise<boolean> {
  const excludePath = path.join(cwd, ".git", "info", "exclude");
  try {
    const current = await fs.readFile(excludePath, "utf8");
    if (current.split(/\r?\n/).some((line) => line.trim() === GROK_GIT_EXCLUDE_ENTRY)) return false;
    const separator = current.length === 0 || current.endsWith("\n") ? "" : "\n";
    await fs.appendFile(excludePath, `${separator}${GROK_GIT_EXCLUDE_ENTRY}\n`);
    return true;
  } catch {
    return false;
  }
}
